version: '3'
services:
  nginx:
    image: nginx:1.13-alpine
    volumes:
      - .:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /usr/share/nginx/html
    ports:
      - 3000:80
  php:
    image: matheusmariano/php-postgres:alpine
    volumes:
      - .:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
  composer:
    image: composer:latest
    volumes:
      - .:/app
  postgres:
    image: postgres:10.3-alpine
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./docker/postgres/.env
